# Generated by Django 5.0.6 on 2026-05-10 08:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.CharField(max_length=50)),
                ('lot_type', models.CharField(choices=[('land', 'Land'), ('house_and_land', 'House & Land'), ('apartment', 'Apartment'), ('townhouse', 'Townhouse'), ('commercial', 'Commercial')], max_length=30)),
                ('is_released', models.BooleanField(default=False, help_text='False=Draft, True=Available (when no active sale)')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('car_spaces', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, help_text='m²', max_digits=10, null=True)),
                ('floor_area', models.DecimalField(blank=True, decimal_places=2, help_text='m²', max_digits=10, null=True)),
                ('aspect', models.CharField(blank=True, max_length=50)),
                ('level', models.PositiveSmallIntegerField(blank=True, help_text='Apartments', null=True)),
                ('building', models.CharField(blank=True, help_text='Apartments / multi-building', max_length=100)),
                ('inclusions', models.TextField(blank=True)),
                ('floor_plan_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['stage', 'lot_number'],
            },
        ),
        migrations.CreateModel(
            name='LotPriceHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('billing_lot_count', models.PositiveIntegerField(blank=True, help_text='Locked at activation', null=True)),
                ('billing_start_date', models.DateField(blank=True, null=True)),
                ('billing_end_date', models.DateField(blank=True, null=True)),
                ('billing_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], max_length=20)),
                ('category', models.CharField(choices=[('hero', 'Hero'), ('gallery', 'Gallery'), ('brochure', 'Brochure'), ('site_map', 'Site Map'), ('floor_plan', 'Floor Plan'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='project_media/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('stage_number', models.PositiveIntegerField()),
                ('expected_release', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['project', 'stage_number'],
            },
        ),
    ]
