# Generated by Django 5.0.6 on 2026-05-10 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lotpricehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lotpricehistory',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='projects.lot'),
        ),
        migrations.AddField(
            model_name='project',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='project',
            name='solicitor',
            field=models.ForeignKey(blank=True, help_text="The developer's legal representative for this project", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_vendor_solicitor', to='contacts.solicitor'),
        ),
        migrations.AddField(
            model_name='projectmedia',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectmedia',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project'),
        ),
        migrations.AddField(
            model_name='lot',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='projects.stage'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organisation', 'id'], name='projects_pr_organis_c4fac0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('project', 'stage_number')},
        ),
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together={('stage', 'lot_number')},
        ),
    ]
