# Generated by Django 5.0.6 on 2026-05-13 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('projects', '0002_project_amenities'),
    ]

    operations = [
    ]
