# Generated by Django 5.0.6 on 2026-05-14 00:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_agency_default_commission_rate_and_more'),
        ('projects', '0003_merge_0002_initial_0002_project_amenities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='LotAgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_lots', to='contacts.agency')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lot_agency', to='projects.lot')),
            ],
            options={
                'verbose_name': 'Lot agency (exclusive)',
                'verbose_name_plural': 'Lot agencies (exclusive)',
                'ordering': ['assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_agencies', to='contacts.agency')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_agencies', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project agency',
                'verbose_name_plural': 'Project agencies',
                'ordering': ['assigned_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectagency',
            constraint=models.UniqueConstraint(fields=('project', 'agency'), name='unique_agency_per_project'),
        ),
    ]
