# Generated by Django 5.0.6 on 2026-05-15 06:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_amenities_alter_projectmedia_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('authority', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pre_lodgement', 'Pre-lodgement'), ('lodged', 'Lodged'), ('under_assessment', 'Under Assessment'), ('approved', 'Approved'), ('conditions_issued', 'Conditions Issued'), ('operational_works', 'Operational Works')], default='pre_lodgement', max_length=30)),
                ('lodgement_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('lapse_date', models.DateField(blank=True, null=True)),
                ('commencement_confirmed', models.BooleanField(default=False)),
                ('commencement_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_applications', to='projects.project')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='development_applications', to='projects.stage')),
            ],
            options={
                'verbose_name': 'Development Application',
                'verbose_name_plural': 'Development Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DAMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone_type', models.CharField(choices=[('commencement', 'Commencement of Works'), ('practical_completion', 'Practical Completion'), ('occupation_cert', 'Occupation Certificate'), ('defects_liability_end', 'Defects Liability End'), ('custom', 'Custom')], max_length=30)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.developmentapplication')),
            ],
            options={
                'verbose_name': 'DA Milestone',
                'verbose_name_plural': 'DA Milestones',
                'ordering': ['planned_date', 'milestone_type'],
            },
        ),
        migrations.CreateModel(
            name='DACondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition_number', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('pre_construction', 'Pre-construction'), ('construction', 'Construction'), ('post_construction', 'Post-construction'), ('ongoing', 'Ongoing')], default='pre_construction', max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('waived', 'Waived')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='da_conditions', to=settings.AUTH_USER_MODEL)),
                ('da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='projects.developmentapplication')),
            ],
            options={
                'verbose_name': 'DA Condition',
                'verbose_name_plural': 'DA Conditions',
                'ordering': ['condition_number', 'created_at'],
            },
        ),
    ]
