# Generated by Django 5.0.6 on 2026-05-18 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_developmentapplication_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DADocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('decision_notice', 'Decision Notice'), ('approved_plans', 'Approved Plans'), ('condition_schedule', 'Condition Schedule'), ('referral_response', 'Referral Response'), ('correspondence', 'Correspondence'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='da_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.developmentapplication')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DA Document',
                'verbose_name_plural': 'DA Documents',
                'ordering': ['category', 'created_at'],
            },
        ),
    ]
