# Generated by Django 5.0.6 on 2026-05-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='notification_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-separated email addresses to CC on all sales advice emails (e.g. developer mailbox).'),
        ),
    ]
