# Generated by Django 5.0.6 on 2026-05-14 06:33

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organisation_notification_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='org_token',
            field=models.CharField(default=secrets.token_urlsafe, help_text='Token for portal webhook authentication (Domain / REA lead ingestion).', max_length=64, unique=True),
        ),
    ]
