# Generated by Django 5.0.6 on 2026-05-10 08:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('inspection', 'Inspection'), ('task', 'Task'), ('note', 'Note')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_date', models.DateTimeField()),
                ('contact_type', models.CharField(choices=[('Buyer', 'Buyer'), ('Agent', 'Agent'), ('Solicitor', 'Solicitor'), ('Referrer', 'Referrer')], max_length=20)),
                ('contact_id', models.UUIDField(help_text='ID of the related Buyer, Agent, Solicitor, or Referrer')),
                ('due_date', models.DateTimeField(blank=True, help_text='Tasks only', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Null = incomplete', null=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-activity_date'],
            },
        ),
    ]
