# Generated by Django 5.0.6 on 2026-05-10 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('core', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='sales.sale'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['organisation', 'id'], name='activities__organis_0c35e2_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['contact_type', 'contact_id'], name='activities__contact_e75500_idx'),
        ),
    ]
