# Generated by Django 5.0.6 on 2026-05-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='contact_id',
            field=models.UUIDField(blank=True, help_text='ID of the related Buyer, Agent, Solicitor, or Referrer', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('Buyer', 'Buyer'), ('Agent', 'Agent'), ('Solicitor', 'Solicitor'), ('Referrer', 'Referrer')], max_length=20, null=True),
        ),
    ]
