# Generated by Django 5.0.6 on 2026-05-12 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_organisation_notification_emails'),
        ('sales', '0003_sale_sales_advice_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAdviceLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('recipients', models.TextField(help_text='Comma-separated list of addresses the email was sent to.')),
                ('error', models.TextField(blank=True, help_text='Error message if send failed.')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organisation')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advice_logs', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Sales Advice Log',
                'ordering': ['-sent_at'],
            },
        ),
    ]
