# Generated by Django 5.0.6 on 2026-05-12 05:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organisation_notification_emails'),
        ('notifications', '0001_initial'),
        ('sales', '0003_sale_sales_advice_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notif_type', models.CharField(choices=[('sale_pending', 'Sale pending approval'), ('sale_approved', 'Sale approved'), ('sale_declined', 'Sale declined'), ('on_hold_expiry', 'On hold expiring soon')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organisation')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', 'recipient', 'is_read'], name='notificatio_organis_bba220_idx')],
            },
        ),
    ]
