# Generated by Django 5.0.6 on 2026-05-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('sale_pending', 'Sale pending approval'), ('sale_approved', 'Sale approved'), ('sale_declined', 'Sale declined'), ('on_hold_expiry', 'On hold expiring soon'), ('due_tomorrow', 'Activity due tomorrow'), ('due_today', 'Activity due today'), ('overdue', 'Activity overdue')], max_length=30),
        ),
        migrations.AlterField(
            model_name='salesadvicelog',
            name='error',
            field=models.TextField(blank=True),
        ),
    ]
