# Generated by Django 5.0.6 on 2026-05-18 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_da_project'),
        ('projects', '0007_developmentapplication_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='projects.developmentapplication'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('sale_pending', 'Sale pending approval'), ('sale_approved', 'Sale approved'), ('sale_declined', 'Sale declined'), ('on_hold_expiry', 'On hold expiring soon'), ('due_tomorrow', 'Activity due tomorrow'), ('due_today', 'Activity due today'), ('overdue', 'Activity overdue'), ('da_lapse_warning', 'DA lapsing soon'), ('da_condition_due_soon', 'DA condition due soon'), ('da_condition_overdue', 'DA condition overdue'), ('da_milestone_overdue', 'DA milestone overdue')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='projects.project'),
        ),
    ]
