# Generated by Django 5.0.6 on 2026-05-10 08:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_type', models.CharField(choices=[('eft', 'EFT'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=20)),
                ('deposit_date', models.DateField()),
                ('deposit_time', models.TimeField()),
                ('attachment', models.FileField(upload_to='sale_documents/deposits/')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('on_hold', 'On Hold'), ('pending', 'Pending'), ('declined', 'Declined'), ('reserved', 'Reserved'), ('contract_issued', 'Contract Issued'), ('exchanged', 'Exchanged'), ('settled', 'Settled'), ('fallen_over', 'Fallen Over')], default='on_hold', max_length=30)),
                ('on_hold_expiry', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id_verified', models.BooleanField(default=False)),
                ('cooling_off_waived', models.BooleanField(default=False)),
                ('cooling_off_expiry', models.DateField(blank=True, null=True)),
                ('subject_to_finance', models.BooleanField(default=False)),
                ('finance_due_date', models.DateField(blank=True, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('fallen_over_at', models.DateTimeField(blank=True, null=True)),
                ('fallen_over_reason', models.CharField(blank=True, choices=[('tubed_buyer', 'Tubed — Buyer Decision'), ('tubed_finance', 'Tubed — Finance'), ('cancelled', 'Cancelled')], max_length=30)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('contract_issued_date', models.DateField(blank=True, null=True)),
                ('contract_document', models.FileField(blank=True, null=True, upload_to='sale_documents/contracts/')),
                ('exchange_date', models.DateField(blank=True, null=True)),
                ('signed_contract', models.FileField(blank=True, null=True, upload_to='sale_documents/signed/')),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('settlement_statement', models.FileField(blank=True, null=True, upload_to='sale_documents/settlement/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('flat', 'Flat')], max_length=20)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('flat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('calculated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('incentive_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('incentive_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='contacts.agent')),
            ],
        ),
    ]
