# Generated by Django 5.0.6 on 2026-05-10 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
        ('projects', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commission',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deposit',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='sale',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='contacts.agent'),
        ),
        migrations.AddField(
            model_name='sale',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='projects.lot'),
        ),
        migrations.AddField(
            model_name='sale',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='sale',
            name='primary_buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_as_primary', to='contacts.buyer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='contacts.referrer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='secondary_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_as_secondary', to='contacts.buyer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='solicitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='contacts.solicitor'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='commission',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='sales.sale'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organisation', 'id'], name='sales_sale_organis_7d34c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'fallen_over'), _negated=True), fields=('lot',), name='unique_active_sale_per_lot'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['organisation', 'id'], name='sales_depos_organis_5aa3f3_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['organisation', 'id'], name='sales_commi_organis_a34feb_idx'),
        ),
    ]
