# Generated by Django 5.0.6 on 2026-05-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sales_advice_document',
            field=models.FileField(blank=True, help_text='Auto-generated sales advice PDF, created on approval.', null=True, upload_to='sale_documents/sales_advice/'),
        ),
    ]
