# Generated by Django 5.0.6 on 2026-05-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='converted_at',
            field=models.DateTimeField(blank=True, help_text='Set automatically when first Sale is created for this prospect', null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='interest_level',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='', help_text='How warm is this prospect?', max_length=10),
        ),
        migrations.AddField(
            model_name='buyer',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes on this prospect'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='preferred_lot_type',
            field=models.CharField(blank=True, help_text='e.g. house_and_land, apartment', max_length=30),
        ),
        migrations.AddField(
            model_name='buyer',
            name='source',
            field=models.CharField(blank=True, choices=[('agent', 'Agent referral'), ('website', 'Website enquiry'), ('display', 'Display suite'), ('referral', 'Personal referral'), ('social', 'Social media'), ('other', 'Other')], default='', help_text='How did this prospect come to us?', max_length=20),
        ),
    ]
