# Generated by Django 5.0.6 on 2026-05-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_buyer_budget_max_buyer_budget_min_buyer_converted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='default_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Percentage (e.g. 2.5000 for 2.5%) or flat amount depending on type', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='default_commission_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('flat', 'Flat amount')], default='', help_text='Default commission type for agents from this agency', max_length=20),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='interest_level',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='preferred_lot_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='source',
            field=models.CharField(blank=True, choices=[('agent', 'Agent referral'), ('website', 'Website enquiry'), ('display', 'Display suite'), ('referral', 'Personal referral'), ('social', 'Social media'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='trustee_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
