# Generated by Django 5.0.6 on 2026-05-14 06:33

import django.db.models.deletion
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_agency_default_commission_rate_and_more'),
        ('core', '0003_organisation_org_token'),
        ('projects', '0004_alter_project_amenities_alter_projectmedia_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryForm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_token', models.CharField(default=secrets.token_urlsafe, help_text='Unique token for the public submission URL.', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='When False, the endpoint returns 404 and creates no prospects.')),
            ],
            options={
                'verbose_name': 'Enquiry form',
                'verbose_name_plural': 'Enquiry forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('source', models.CharField(choices=[('website_form', 'Website enquiry form'), ('portal', 'Portal (Domain / REA)'), ('walk_in', 'Walk-in'), ('phone', 'Phone enquiry'), ('referral', 'Referral'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('converted', 'Converted'), ('lost', 'Lost')], default='active', max_length=20)),
                ('lost_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_returning_buyer', models.BooleanField(default=False, help_text='Set True when matched to an existing Buyer on creation.')),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='buyer',
            name='is_return_buyer',
            field=models.BooleanField(default=False, help_text='True when this buyer has more than one sale linked to their record.'),
        ),
        migrations.AddIndex(
            model_name='buyer',
            index=models.Index(fields=['organisation', 'email'], name='contacts_bu_organis_9965ed_idx'),
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='default_assigned_to',
            field=models.ForeignKey(blank=True, help_text='New prospects auto-assigned to this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_form', to='projects.project'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prospects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prospect',
            name='buyer',
            field=models.ForeignKey(blank=True, help_text='Linked Buyer — set on match (returning) or conversion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='contacts.buyer'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='projects.lot'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['organisation', 'status'], name='contacts_pr_organis_d3751e_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['organisation', 'email'], name='contacts_pr_organis_0f8469_idx'),
        ),
    ]
