# Generated by Django 5.0.6 on 2026-05-15 04:07

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_enquiryform_prospect_buyer_is_return_buyer_and_more'),
        ('core', '0003_organisation_org_token'),
        ('projects', '0004_alter_project_amenities_alter_projectmedia_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiryform',
            options={},
        ),
        migrations.AddField(
            model_name='prospect',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='purchase_intent',
            field=models.CharField(blank=True, choices=[('investor', 'Investor'), ('owner_occupier', 'Owner occupier'), ('undecided', 'Undecided')], default='undecided', max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiryform',
            name='default_assigned_to',
            field=models.ForeignKey(blank=True, help_text='New prospects from this form are auto-assigned to this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_form_defaults', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enquiryform',
            name='form_token',
            field=models.CharField(default=secrets.token_urlsafe, help_text='Unique URL-safe token used in the public submission endpoint.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiryform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_records', to='contacts.buyer'),
        ),
        migrations.AddIndex(
            model_name='enquiryform',
            index=models.Index(fields=['form_token'], name='contacts_en_form_to_138ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['organisation', 'id'], name='contacts_pr_organis_7f0879_idx'),
        ),
    ]
